# frozen_string_literal: true

module Quartet::Builders
  class Gemfile < Quartet::Builders::Builder
    def initialize
      @name_override = 'Gemfile'
      @directory = ''
      @file_type = ''
    end

    def build(app_name)
      %{# frozen_string_literal: true

# Gemfile for #{app_name} generated by Quartet

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/\#{repo_name}" }

gem "sinatra", "~> 2.0"

gem "sinatra-activerecord", "~> 2.0"

gem "mysql2", "~> 0.5.3"

gem "puma", "~> 5.3.1"

gem "rake", "~> 13.0"

gem "irb", "~> 1.2"
}
    end
  end
end
